packages:
  - workflow
  - model
  - ui
  - test
  - .

catalog:
  "@platforma-sdk/model": ^1.5.40
  "@platforma-sdk/ui-vue": ^1.5.38
  "@platforma-sdk/workflow-tengo": ^1.3.0
  "@platforma-sdk/block-tools": ^2.3.12
  "@platforma-sdk/test": ^1.5.43
  "@platforma-sdk/tengo-builder": ^1.14.13

  
  "vue": ^3.4.34
  "vue-tsc": ^2.0.29
  
  "typescript": ^5.5.4
  "tsup": ~8.1.2

  "vite": ^5.3.5
  "vitest": ^2.0.4
  "@vitejs/plugin-vue": ^5.1.0

  "@changesets/cli": ^2.27.7
