packages:
  - workflow
  - model
  - ui
  - test
  - .

catalog:
  "@platforma-sdk/model": ^1.7.20
  "@platforma-sdk/ui-vue": ^1.7.46
  "@platforma-sdk/workflow-tengo": ^1.7.4
  "@platforma-sdk/block-tools": ^2.3.21
  "@platforma-sdk/test": ^1.7.48
  "@platforma-sdk/tengo-builder": ^1.16.1
  "@platforma-sdk/package-builder": ^2.10.6
  
  "@platforma-open/milaboratories.java-debug.software": ^1.0.0
  "@platforma-open/milaboratories.runenv-java-corretto": ^1.0.2

  "vue": ^3.4.34
  "vue-tsc": ^2.0.29
  
  "typescript": ^5.5.4
  "tsup": ~8.1.2

  "vite": ^5.3.5
  "vitest": ^2.0.4
  "@vitejs/plugin-vue": ^5.1.0

  "@changesets/cli": ^2.27.7
